name: 'Continuous Integration'

on:
    pull_request:
        branches:
            - 'main'
    push:
        branches:
            - 'main'

permissions:
    contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
    code-style:
        name: 'Code style'
        runs-on: 'ubuntu-22.04'
        strategy:
            matrix:
                php: ['8.1']
        steps:
            - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
              with:
                  persist-credentials: false
            - uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # 2.37.2
              with:
                  coverage: 'none'
                  php-version: '${{ matrix.php }}'

            - name: 'Determine composer cache directory'
              id: 'determine-composer-cache-directory'
              run: 'echo "::set-output name=directory::$(composer config cache-dir)"'
            - name: 'Cache dependencies installed with composer'
              uses: 'actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830' # v4
              with:
                  path: |
                      ${{ steps.determine-composer-cache-directory.outputs.directory }}
                      ${{ github.workspace }}/vendor
                  key: "php-${{ matrix.php }}-${{ hashFiles('composer.lock') }}"
                  restore-keys: 'php-${{ matrix.php }}-'
            - uses: ramsey/composer-install@a8d0d959dab41457692a5e2041bd9b757a119e3f # 3.2.1
              with:
                  dependency-versions: 'highest'
            - run: './vendor/bin/php-cs-fixer fix --dry-run --diff --verbose'

    static-analysis:
        name: 'Static analysis'
        runs-on: 'ubuntu-22.04'
        strategy:
            matrix:
                php: ['8.1']
        steps:
            - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
              with:
                  persist-credentials: false
            - uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # 2.37.2
              with:
                  coverage: 'none'
                  php-version: '${{ matrix.php }}'

            - name: 'Determine composer cache directory'
              id: 'determine-composer-cache-directory'
              run: 'echo "::set-output name=directory::$(composer config cache-dir)"'
            - name: 'Cache dependencies installed with composer'
              uses: 'actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830' # v4
              with:
                  path: |
                      ${{ steps.determine-composer-cache-directory.outputs.directory }}
                      ${{ github.workspace }}/vendor
                  key: "php-${{ matrix.php }}-${{ hashFiles('composer.lock') }}"
                  restore-keys: 'php-${{ matrix.php }}-'
            - uses: ramsey/composer-install@a8d0d959dab41457692a5e2041bd9b757a119e3f # 3.2.1
              with:
                  dependency-versions: 'highest'
            - run: './vendor/bin/phpstan'

    phpunit:
        name: 'PHPUnit'
        runs-on: 'ubuntu-22.04'
        strategy:
            matrix:
                php: ['8.1']
        steps:
            - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
              with:
                  persist-credentials: false
            - uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # 2.37.2
              with:
                  coverage: 'none'
                  php-version: '${{ matrix.php }}'

            - name: 'Determine composer cache directory'
              id: 'determine-composer-cache-directory'
              run: 'echo "::set-output name=directory::$(composer config cache-dir)"'
            - name: 'Cache dependencies installed with composer'
              uses: 'actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830' # v4
              with:
                  path: |
                      ${{ steps.determine-composer-cache-directory.outputs.directory }}
                      ${{ github.workspace }}/vendor
                  key: "php-${{ matrix.php }}-${{ hashFiles('composer.lock') }}"
                  restore-keys: 'php-${{ matrix.php }}-'
            - uses: ramsey/composer-install@a8d0d959dab41457692a5e2041bd9b757a119e3f # 3.2.1
              with:
                  dependency-versions: 'highest'
            - run: './vendor/bin/phpunit'
